name: libcoder
description: A general-purpose serialization framework for Dart.
repository: https://github.com/celest-dev/dart-packages/tree/main/packages/libcoder
version: 0.0.3

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.10.0

dev_dependencies:
  lints: ">=3.0.0 <5.0.0"
  test: ^1.24.0
