name: libcoder
description: A general-purpose serialization framework for Dart.
repository: https://github.com/celest-dev/dart-packages/tree/main/packages/libcoder
version: 0.0.4-wip

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  meta: ^1.14.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
