name: http_sfv
description: Dart implementation of Structured Field Values for HTTP (RFC8941)
repository: https://github.com/celest-dev/dart-packages/tree/main/packages/http_sfv
version: 0.1.1-wip

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  collection: ^1.18.0
  meta: ^1.10.0
  source_span: ^1.10.0

dev_dependencies:
  base32: ^2.1.3
  lints: ^5.0.0
  path: ^1.9.0
  test: ^1.24.0
