name: native_authentication
description: Native bindings for platform-specific authentication APIs like ASWebAuthenticationSession and Chrome Custom Tabs.
version: 0.1.0+2
repository: https://github.com/celest-dev/dart-packages/tree/main/packages/native/authentication

environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  ffi: ^2.1.3
  jni: ^0.11.0
  logging: ^1.2.0
  meta: ^1.12.0
  native_assets_cli: ^0.7.2
  native_toolchain_c: ^0.5.2
  objective_c: ^2.0.0
  path: ^1.9.0
  stream_transform: ^2.1.0
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  ffigen: ^14.0.0
  test: ^1.20.0
  lints: ^4.0.0
  jnigen: ^0.11.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
