name: native_authentication
description: Native bindings for platform-specific authentication APIs like ASWebAuthenticationSession and Chrome Custom Tabs.
version: 0.1.5
repository: https://github.com/celest-dev/dart-packages/tree/main/packages/native/authentication

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

# Explicitly declare platform support to help `pana`
platforms:
  web:
  windows:
  macos:
  linux:
  ios:
  android:

dependencies:
  ffi: ^2.1.3
  jni: ^0.14.0
  logging: ^1.2.0
  meta: ^1.12.0
  objective_c: ^8.0.0
  path: ^1.9.0
  stream_transform: ^2.1.0
  web: ^1.0.0

dev_dependencies:
  ffigen: ^19.0.0
  test: ^1.20.0
  lints: ^5.1.1
  jnigen: ^0.14.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
