name: native_storage
description: A Dart-only package for accessing platform-native storage functionality.
version: 0.4.0
repository: https://github.com/celest-dev/dart-packages/tree/main/packages/native/storage

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

# Explicitly declare platform support to help `pana`
platforms:
  web:
  windows:
  macos:
  linux:
  ios:
  android:

dependencies:
  ffi: ^2.1.2
  jni: ^0.14.0
  logging: ^1.2.0
  meta: ^1.11.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  web: ^1.0.0
  win32: ^5.4.0
  win32_registry: ^2.1.0
  windows_applicationmodel: ^0.2.0
  xdg_directories: ^1.0.4

dev_dependencies:
  ffigen: ^19.0.0
  jnigen: ^0.14.2
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
