name: native_authentication_example
description: "Demonstrates how to use the native_authentication plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  native_authentication:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
