name: cloud_http
description: Utilities for running Dart server applications in cloud environments.
repository: https://github.com/celest-dev/dart-packages/tree/main/packages/cloud_http
version: 0.1.1

environment:
  sdk: ^3.5.0

dependencies:
  convert: ^3.1.1
  http_sfv: ^0.1.0
  shelf: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
