name: http_sfv
on:
  pull_request:
    paths:
      - ".github/workflows/http_sfv.yaml"
      - "packages/http_sfv/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        sdk:
          - stable
          - "3.3"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Git Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # 4.2.1
        with:
          submodules: recursive
      - name: Setup Dart
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672 # 1.6.5
        with:
          sdk: ${{ matrix.sdk }}
      - name: Get Packages
        working-directory: packages/http_sfv
        run: dart pub get
      - name: Analyze
        working-directory: packages/http_sfv
        run: dart analyze
      - name: Format
        working-directory: packages/http_sfv
        run: dart format --set-exit-if-changed .
      - name: Test
        working-directory: packages/http_sfv
        run: dart test
