name: native_authentication
on:
  pull_request:
    paths:
      - ".github/workflows/native_authentication.yaml"
      - "packages/native/authentication/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/native/authentication

jobs:
  build:
    runs-on: macos-latest-xlarge
    timeout-minutes: 25
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Setup Flutter
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # 2.19.0
        with:
          channel: stable
          cache: true
      - name: Get Packages
        run: flutter pub get
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Build Example (iOS)
        run: flutter build ios --no-codesign
        working-directory: packages/native/authentication/example
      - name: Build Example (Web)
        run: flutter build web
        working-directory: packages/native/authentication/example
