name: native_authentication
on:
  pull_request:
    paths:
      - ".github/workflows/native_authentication.yaml"
      - "packages/native/authentication/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/native/authentication

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 25
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Setup Flutter
        uses: subosito/flutter-action@395322a6cded4e9ed503aebd4cc1965625f8e59a # 2.20.0
        with:
          channel: stable
          cache: true
      - name: Get Packages
        run: flutter pub get
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Build Example (iOS)
        run: flutter build ios --no-codesign
        working-directory: packages/native/authentication/example
      - name: Build Example (Web)
        run: flutter build web
        working-directory: packages/native/authentication/example
  test_darwin:
    runs-on: macos-latest-xlarge # Tests timeout on smaller `macos-latest` runner
    timeout-minutes: 20
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Setup Flutter
        uses: subosito/flutter-action@395322a6cded4e9ed503aebd4cc1965625f8e59a # 2.20.0
        with:
          cache: true
      - name: Get Packages
        working-directory: packages/native/authentication
        run: dart pub get
      - name: Test
        working-directory: packages/native/authentication
        run: dart test
      - name: Get Packages (Example)
        working-directory: packages/native/authentication/example
        run: flutter pub get
      - name: Setup iOS Simulator
        run: |
          RUNTIME=$(xcrun simctl list runtimes | grep 'iOS 18' | tail -n 1 | cut -d' ' -f 7)
          echo "Using runtime: $RUNTIME"
          xcrun simctl create ios 'iPhone 16 Pro Max' $RUNTIME
          echo "Booting simulator"
          xcrun simctl boot ios
          echo "Booted simulator"
      - name: Test (iOS)
        working-directory: packages/native/authentication/example
        run: flutter test -d ios integration_test/integration_test.dart
      - name: Test (macOS)
        working-directory: packages/native/authentication/example
        run: flutter test -d macos integration_test/integration_test.dart
  test_android:
    runs-on: ubuntu-large
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Setup Flutter
        uses: subosito/flutter-action@395322a6cded4e9ed503aebd4cc1965625f8e59a # 2.20.0
        with:
          cache: true
      - name: Get Packages (Example)
        working-directory: packages/native/authentication/example
        run: flutter pub get
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Test (API 35)
        uses: ReactiveCircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # 2.34.0
        with:
          # Matches Flutter compileSdkVersion
          api-level: 35
          arch: x86_64
          script: cd packages/native/authentication/example && flutter test -d emulator integration_test/integration_test.dart
      - name: Test (API 21)
        uses: ReactiveCircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # 2.34.0
        with:
          # Minimum supported API level
          api-level: 21
          arch: x86_64
          script: cd packages/native/authentication/example && flutter test -d emulator integration_test/integration_test.dart
  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Setup Flutter
        uses: subosito/flutter-action@395322a6cded4e9ed503aebd4cc1965625f8e59a # 2.20.0
        with:
          cache: true
      - name: Install Build Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - name: Get Packages
        working-directory: packages/native/authentication
        run: dart pub get
      - name: Test
        working-directory: packages/native/authentication
        run: dart test
      - name: Get Packages (Example)
        working-directory: packages/native/authentication/example
        run: flutter pub get
      - name: Test (Linux)
        working-directory: packages/native/authentication/example
        run: |
          # Headless tests require virtual display for the linux tests to run.
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          flutter test -d linux integration_test/integration_test.dart
  test_windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Setup Flutter
        uses: subosito/flutter-action@395322a6cded4e9ed503aebd4cc1965625f8e59a # 2.20.0
        with:
          cache: true
      - name: Get Packages
        working-directory: packages/native/authentication
        run: dart pub get --no-example
      - name: Test
        working-directory: packages/native/authentication
        run: dart test
      - name: Get Packages (Example)
        working-directory: packages/native/authentication/example
        run: flutter pub get
      - name: Test (Windows)
        working-directory: packages/native/authentication/example
        run: flutter test -d windows integration_test/integration_test.dart
